import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const COLLEGES = [
  // === CALIFORNIA (12) ===
  { name: 'Stanford University', location: 'Stanford, CA', state: 'CA', college_type: 'private', acceptance_rate: 3.9, sat_range_low: 1500, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 17876, tuition_in_state: 62484, tuition_out_state: 62484, graduation_rate: 96, stem_ranking: 'Top 3 nationally', top_stem_programs: ['Computer Science', 'Engineering', 'Biology', 'Mathematics', 'Physics'], notable_features: ['Silicon Valley location', 'Undergraduate research', 'Need-blind admissions'], has_volleyball: true, volleyball_division: 'D1', website: 'https://stanford.edu' },
  { name: 'Caltech', location: 'Pasadena, CA', state: 'CA', college_type: 'private', acceptance_rate: 3.2, sat_range_low: 1530, sat_range_high: 1580, act_range_low: 35, act_range_high: 36, enrollment: 2397, tuition_in_state: 63402, tuition_out_state: 63402, graduation_rate: 94, stem_ranking: 'Top 5 nationally', top_stem_programs: ['Physics', 'Engineering', 'Computer Science', 'Chemistry', 'Biology'], notable_features: ['100% STEM focused', 'JPL/NASA partnership', 'Small class sizes'], has_volleyball: false, volleyball_division: null, website: 'https://caltech.edu' },
  { name: 'UC Berkeley', location: 'Berkeley, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 11.6, sat_range_low: 1390, sat_range_high: 1530, act_range_low: 31, act_range_high: 35, enrollment: 45307, tuition_in_state: 14312, tuition_out_state: 44066, graduation_rate: 93, stem_ranking: 'Top 5 public', top_stem_programs: ['EECS', 'Computer Science', 'Bioengineering', 'Chemistry', 'Data Science'], notable_features: ['Top public university', 'Bay Area tech ecosystem', 'Strong research'], has_volleyball: true, volleyball_division: 'D1', website: 'https://berkeley.edu' },
  { name: 'UCLA', location: 'Los Angeles, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 8.8, sat_range_low: 1360, sat_range_high: 1520, act_range_low: 31, act_range_high: 35, enrollment: 46430, tuition_in_state: 13401, tuition_out_state: 43003, graduation_rate: 92, stem_ranking: 'Top 10 public', top_stem_programs: ['Computer Science', 'Engineering', 'Life Sciences', 'Mathematics', 'Neuroscience'], notable_features: ['Most applied-to US university', 'Strong athletics', 'Research opportunities'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ucla.edu' },
  { name: 'UC San Diego', location: 'La Jolla, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 24.7, sat_range_low: 1330, sat_range_high: 1510, act_range_low: 30, act_range_high: 34, enrollment: 42006, tuition_in_state: 14418, tuition_out_state: 44130, graduation_rate: 88, stem_ranking: 'Top 15 public', top_stem_programs: ['Bioengineering', 'Computer Science', 'Cognitive Science', 'Marine Biology', 'Nanoengineering'], notable_features: ['College system', 'Beach campus', 'Strong biotech research'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ucsd.edu' },
  { name: 'UC Davis', location: 'Davis, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 37.3, sat_range_low: 1210, sat_range_high: 1430, act_range_low: 27, act_range_high: 33, enrollment: 40031, tuition_in_state: 14634, tuition_out_state: 44249, graduation_rate: 86, stem_ranking: 'Top 20 public', top_stem_programs: ['Agricultural Science', 'Veterinary Science', 'Biology', 'Environmental Science', 'Computer Science'], notable_features: ['Top vet school', 'Sustainability focus', 'Large campus'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ucdavis.edu' },
  { name: 'UC Irvine', location: 'Irvine, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 21.0, sat_range_low: 1250, sat_range_high: 1470, act_range_low: 28, act_range_high: 34, enrollment: 36908, tuition_in_state: 13727, tuition_out_state: 43467, graduation_rate: 85, stem_ranking: 'Top 25 public', top_stem_programs: ['Computer Science', 'Informatics', 'Engineering', 'Biological Sciences', 'Data Science'], notable_features: ['Game design program', 'Close to tech industry', 'Esports'], has_volleyball: true, volleyball_division: 'D1', website: 'https://uci.edu' },
  { name: 'UC Santa Barbara', location: 'Santa Barbara, CA', state: 'CA', college_type: 'public_uc', acceptance_rate: 25.9, sat_range_low: 1290, sat_range_high: 1490, act_range_low: 29, act_range_high: 34, enrollment: 26179, tuition_in_state: 14391, tuition_out_state: 44145, graduation_rate: 84, stem_ranking: 'Top 20 public', top_stem_programs: ['Materials Science', 'Physics', 'Computer Science', 'Chemical Engineering', 'Marine Science'], notable_features: ['Beach campus', 'Nobel laureate faculty', 'Strong physics'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ucsb.edu' },
  { name: 'USC', location: 'Los Angeles, CA', state: 'CA', college_type: 'private', acceptance_rate: 12.0, sat_range_low: 1430, sat_range_high: 1540, act_range_low: 33, act_range_high: 35, enrollment: 49500, tuition_in_state: 66640, tuition_out_state: 66640, graduation_rate: 92, stem_ranking: 'Top 20 private', top_stem_programs: ['Computer Science', 'Electrical Engineering', 'Biomedical Engineering', 'Game Design', 'Astronautical Engineering'], notable_features: ['Viterbi School of Engineering', 'LA location', 'Strong alumni network'], has_volleyball: true, volleyball_division: 'D1', website: 'https://usc.edu' },
  { name: 'Harvey Mudd College', location: 'Claremont, CA', state: 'CA', college_type: 'private', acceptance_rate: 13.4, sat_range_low: 1470, sat_range_high: 1560, act_range_low: 34, act_range_high: 36, enrollment: 902, tuition_in_state: 64427, tuition_out_state: 64427, graduation_rate: 93, stem_ranking: 'Top STEM liberal arts', top_stem_programs: ['Engineering', 'Computer Science', 'Physics', 'Mathematics', 'Biology'], notable_features: ['100% STEM', 'Tiny classes', 'Claremont Consortium'], has_volleyball: false, volleyball_division: 'D3', website: 'https://hmc.edu' },
  { name: 'Cal Poly San Luis Obispo', location: 'San Luis Obispo, CA', state: 'CA', college_type: 'public_csu', acceptance_rate: 30.0, sat_range_low: 1270, sat_range_high: 1440, act_range_low: 28, act_range_high: 33, enrollment: 22028, tuition_in_state: 11259, tuition_out_state: 22719, graduation_rate: 83, stem_ranking: 'Top teaching university', top_stem_programs: ['Engineering', 'Architecture', 'Computer Science', 'Agriculture', 'Construction Management'], notable_features: ['Learn by Doing', 'Beautiful location', 'Industry connections'], has_volleyball: true, volleyball_division: 'D1', website: 'https://calpoly.edu' },
  { name: 'Santa Clara University', location: 'Santa Clara, CA', state: 'CA', college_type: 'private', acceptance_rate: 49.0, sat_range_low: 1310, sat_range_high: 1470, act_range_low: 30, act_range_high: 33, enrollment: 9015, tuition_in_state: 59241, tuition_out_state: 59241, graduation_rate: 91, stem_ranking: 'Strong regional', top_stem_programs: ['Computer Science', 'Electrical Engineering', 'Bioengineering', 'Web Development'], notable_features: ['Silicon Valley heart', 'Jesuit education', 'Strong internship pipeline'], has_volleyball: true, volleyball_division: 'D1', website: 'https://scu.edu' },

  // === NATIONAL ELITE (20) ===
  { name: 'MIT', location: 'Cambridge, MA', state: 'MA', college_type: 'private', acceptance_rate: 3.5, sat_range_low: 1520, sat_range_high: 1580, act_range_low: 35, act_range_high: 36, enrollment: 11858, tuition_in_state: 59750, tuition_out_state: 59750, graduation_rate: 96, stem_ranking: '#1 Engineering & CS', top_stem_programs: ['Computer Science', 'Engineering', 'Mathematics', 'Physics', 'AI/ML'], notable_features: ['Maker culture', 'Startup ecosystem', 'Need-blind'], has_volleyball: true, volleyball_division: 'D3', website: 'https://mit.edu' },
  { name: 'Carnegie Mellon University', location: 'Pittsburgh, PA', state: 'PA', college_type: 'private', acceptance_rate: 11.0, sat_range_low: 1490, sat_range_high: 1560, act_range_low: 34, act_range_high: 36, enrollment: 15818, tuition_in_state: 62260, tuition_out_state: 62260, graduation_rate: 92, stem_ranking: 'Top 5 CS', top_stem_programs: ['Computer Science', 'Robotics', 'AI', 'Electrical Engineering', 'Information Systems'], notable_features: ['#1 Robotics', 'Strong arts+tech', 'Silicon Valley pipeline'], has_volleyball: true, volleyball_division: 'D3', website: 'https://cmu.edu' },
  { name: 'Georgia Tech', location: 'Atlanta, GA', state: 'GA', college_type: 'public', acceptance_rate: 17.0, sat_range_low: 1390, sat_range_high: 1530, act_range_low: 32, act_range_high: 35, enrollment: 44000, tuition_in_state: 12682, tuition_out_state: 33794, graduation_rate: 90, stem_ranking: 'Top 5 engineering', top_stem_programs: ['Computer Science', 'Aerospace Engineering', 'Biomedical Engineering', 'Industrial Engineering'], notable_features: ['Co-op programs', 'Atlanta tech hub', 'Affordable for public'], has_volleyball: true, volleyball_division: 'D1', website: 'https://gatech.edu' },
  { name: 'University of Illinois Urbana-Champaign', location: 'Champaign, IL', state: 'IL', college_type: 'public', acceptance_rate: 44.0, sat_range_low: 1310, sat_range_high: 1500, act_range_low: 29, act_range_high: 34, enrollment: 56000, tuition_in_state: 16004, tuition_out_state: 34312, graduation_rate: 87, stem_ranking: 'Top 10 CS & Engineering', top_stem_programs: ['Computer Science', 'Electrical Engineering', 'Physics', 'Materials Science'], notable_features: ['Grainger College of Engineering', 'Big Ten athletics', 'Strong CS'], has_volleyball: true, volleyball_division: 'D1', website: 'https://illinois.edu' },
  { name: 'Purdue University', location: 'West Lafayette, IN', state: 'IN', college_type: 'public', acceptance_rate: 53.0, sat_range_low: 1200, sat_range_high: 1440, act_range_low: 27, act_range_high: 33, enrollment: 50884, tuition_in_state: 9992, tuition_out_state: 28794, graduation_rate: 83, stem_ranking: 'Top 10 engineering', top_stem_programs: ['Aerospace Engineering', 'Computer Science', 'Mechanical Engineering', 'Pharmacy'], notable_features: ['Astronaut alumni', 'Affordable', 'Engineering focused'], has_volleyball: true, volleyball_division: 'D1', website: 'https://purdue.edu' },
  { name: 'University of Michigan', location: 'Ann Arbor, MI', state: 'MI', college_type: 'public', acceptance_rate: 18.0, sat_range_low: 1380, sat_range_high: 1540, act_range_low: 32, act_range_high: 35, enrollment: 47907, tuition_in_state: 17786, tuition_out_state: 57273, graduation_rate: 93, stem_ranking: 'Top 10 public', top_stem_programs: ['Computer Science', 'Engineering', 'Biomedical Sciences', 'Data Science'], notable_features: ['Ross School of Business', 'Big Ten', 'Strong research'], has_volleyball: true, volleyball_division: 'D1', website: 'https://umich.edu' },
  { name: 'Cornell University', location: 'Ithaca, NY', state: 'NY', college_type: 'private', acceptance_rate: 7.9, sat_range_low: 1470, sat_range_high: 1560, act_range_low: 34, act_range_high: 35, enrollment: 25898, tuition_in_state: 65204, tuition_out_state: 65204, graduation_rate: 95, stem_ranking: 'Top 10 Ivy STEM', top_stem_programs: ['Computer Science', 'Engineering', 'Biological Sciences', 'Hotel Administration'], notable_features: ['Ivy League', 'Land-grant mission', 'Beautiful campus'], has_volleyball: true, volleyball_division: 'D1', website: 'https://cornell.edu' },
  { name: 'Princeton University', location: 'Princeton, NJ', state: 'NJ', college_type: 'private', acceptance_rate: 3.7, sat_range_low: 1510, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 8623, tuition_in_state: 59710, tuition_out_state: 59710, graduation_rate: 98, stem_ranking: 'Top 5 research', top_stem_programs: ['Computer Science', 'Mathematics', 'Physics', 'Molecular Biology', 'Engineering'], notable_features: ['Generous financial aid', 'No graduate TAs', 'Senior thesis'], has_volleyball: true, volleyball_division: 'D1', website: 'https://princeton.edu' },
  { name: 'Columbia University', location: 'New York, NY', state: 'NY', college_type: 'private', acceptance_rate: 3.9, sat_range_low: 1500, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 36649, tuition_in_state: 66139, tuition_out_state: 66139, graduation_rate: 95, stem_ranking: 'Top 10 Ivy', top_stem_programs: ['Computer Science', 'Data Science', 'Biomedical Engineering', 'Applied Mathematics'], notable_features: ['NYC location', 'Core Curriculum', 'Dual degree programs'], has_volleyball: true, volleyball_division: 'D1', website: 'https://columbia.edu' },
  { name: 'Johns Hopkins University', location: 'Baltimore, MD', state: 'MD', college_type: 'private', acceptance_rate: 7.4, sat_range_low: 1500, sat_range_high: 1560, act_range_low: 34, act_range_high: 36, enrollment: 6256, tuition_in_state: 63340, tuition_out_state: 63340, graduation_rate: 94, stem_ranking: '#1 Biomedical', top_stem_programs: ['Biomedical Engineering', 'Public Health', 'Neuroscience', 'Computer Science'], notable_features: ['#1 research spending', 'Pre-med pipeline', 'Applied Physics Lab'], has_volleyball: true, volleyball_division: 'D3', website: 'https://jhu.edu' },
  { name: 'Duke University', location: 'Durham, NC', state: 'NC', college_type: 'private', acceptance_rate: 5.0, sat_range_low: 1490, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 17620, tuition_in_state: 65486, tuition_out_state: 65486, graduation_rate: 96, stem_ranking: 'Top 15', top_stem_programs: ['Biomedical Engineering', 'Computer Science', 'Electrical Engineering', 'Environmental Science'], notable_features: ['Duke Lemur Center', 'Strong athletics', 'Research Triangle'], has_volleyball: true, volleyball_division: 'D1', website: 'https://duke.edu' },
  { name: 'Northwestern University', location: 'Evanston, IL', state: 'IL', college_type: 'private', acceptance_rate: 7.0, sat_range_low: 1490, sat_range_high: 1560, act_range_low: 34, act_range_high: 35, enrollment: 22601, tuition_in_state: 64887, tuition_out_state: 64887, graduation_rate: 95, stem_ranking: 'Top 15', top_stem_programs: ['Engineering', 'Computer Science', 'Materials Science', 'Neuroscience'], notable_features: ['McCormick Engineering', 'Chicago proximity', 'Quarter system'], has_volleyball: true, volleyball_division: 'D1', website: 'https://northwestern.edu' },
  { name: 'Rice University', location: 'Houston, TX', state: 'TX', college_type: 'private', acceptance_rate: 7.7, sat_range_low: 1490, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 8285, tuition_in_state: 58128, tuition_out_state: 58128, graduation_rate: 94, stem_ranking: 'Top 15', top_stem_programs: ['Computer Science', 'Engineering', 'Nanotechnology', 'Bioengineering'], notable_features: ['Residential colleges', 'Houston space industry', 'Small classes'], has_volleyball: true, volleyball_division: 'D1', website: 'https://rice.edu' },
  { name: 'University of Pennsylvania', location: 'Philadelphia, PA', state: 'PA', college_type: 'private', acceptance_rate: 5.4, sat_range_low: 1500, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 28201, tuition_in_state: 63452, tuition_out_state: 63452, graduation_rate: 96, stem_ranking: 'Top 10 Ivy', top_stem_programs: ['Computer Science', 'Bioengineering', 'Systems Engineering', 'Wharton + STEM'], notable_features: ['Wharton crossover', 'M&T dual degree', 'Ivy League'], has_volleyball: true, volleyball_division: 'D1', website: 'https://upenn.edu' },
  { name: 'Yale University', location: 'New Haven, CT', state: 'CT', college_type: 'private', acceptance_rate: 4.6, sat_range_low: 1500, sat_range_high: 1570, act_range_low: 34, act_range_high: 36, enrollment: 14776, tuition_in_state: 64700, tuition_out_state: 64700, graduation_rate: 97, stem_ranking: 'Top 15', top_stem_programs: ['Computer Science', 'Molecular Biology', 'Physics', 'Environmental Engineering'], notable_features: ['Residential colleges', 'Liberal arts + STEM', 'Need-blind'], has_volleyball: true, volleyball_division: 'D1', website: 'https://yale.edu' },
  { name: 'Harvard University', location: 'Cambridge, MA', state: 'MA', college_type: 'private', acceptance_rate: 3.2, sat_range_low: 1500, sat_range_high: 1580, act_range_low: 34, act_range_high: 36, enrollment: 30631, tuition_in_state: 59076, tuition_out_state: 59076, graduation_rate: 98, stem_ranking: 'Top 5', top_stem_programs: ['Computer Science', 'Applied Mathematics', 'Biomedical Engineering', 'Statistics'], notable_features: ['Most generous financial aid', 'Crimson brand', 'Research opportunities'], has_volleyball: true, volleyball_division: 'D1', website: 'https://harvard.edu' },

  // === STRONG STEM PUBLICS (18) ===
  { name: 'UT Austin', location: 'Austin, TX', state: 'TX', college_type: 'public', acceptance_rate: 31.0, sat_range_low: 1230, sat_range_high: 1470, act_range_low: 28, act_range_high: 34, enrollment: 52384, tuition_in_state: 11448, tuition_out_state: 41070, graduation_rate: 87, stem_ranking: 'Top 10 CS', top_stem_programs: ['Computer Science', 'Engineering', 'Data Science', 'Physics'], notable_features: ['Austin tech scene', 'Huge alumni network', 'Cockrell Engineering'], has_volleyball: true, volleyball_division: 'D1', website: 'https://utexas.edu' },
  { name: 'University of Washington', location: 'Seattle, WA', state: 'WA', college_type: 'public', acceptance_rate: 48.0, sat_range_low: 1270, sat_range_high: 1470, act_range_low: 28, act_range_high: 34, enrollment: 61581, tuition_in_state: 12076, tuition_out_state: 40740, graduation_rate: 84, stem_ranking: 'Top 10 CS', top_stem_programs: ['Computer Science', 'Engineering', 'Bioengineering', 'Information Science'], notable_features: ['Seattle tech hub', 'Amazon/Microsoft/Google pipeline', 'Paul Allen School'], has_volleyball: true, volleyball_division: 'D1', website: 'https://washington.edu' },
  { name: 'University of Wisconsin-Madison', location: 'Madison, WI', state: 'WI', college_type: 'public', acceptance_rate: 49.0, sat_range_low: 1290, sat_range_high: 1470, act_range_low: 28, act_range_high: 33, enrollment: 49066, tuition_in_state: 11205, tuition_out_state: 39427, graduation_rate: 88, stem_ranking: 'Top 20 public', top_stem_programs: ['Computer Science', 'Engineering', 'Biochemistry', 'Genetics'], notable_features: ['Big Ten', 'Strong research', 'Vibrant college town'], has_volleyball: true, volleyball_division: 'D1', website: 'https://wisc.edu' },
  { name: 'Virginia Tech', location: 'Blacksburg, VA', state: 'VA', college_type: 'public', acceptance_rate: 57.0, sat_range_low: 1210, sat_range_high: 1400, act_range_low: 27, act_range_high: 32, enrollment: 38167, tuition_in_state: 14698, tuition_out_state: 36090, graduation_rate: 86, stem_ranking: 'Top 20 engineering', top_stem_programs: ['Engineering', 'Computer Science', 'Architecture', 'Natural Resources'], notable_features: ['Ut Prosim motto', 'Corps of Cadets', 'Innovation Campus'], has_volleyball: true, volleyball_division: 'D1', website: 'https://vt.edu' },
  { name: 'University of Maryland', location: 'College Park, MD', state: 'MD', college_type: 'public', acceptance_rate: 45.0, sat_range_low: 1310, sat_range_high: 1490, act_range_low: 30, act_range_high: 34, enrollment: 41200, tuition_in_state: 11233, tuition_out_state: 38636, graduation_rate: 87, stem_ranking: 'Top 20 public', top_stem_programs: ['Computer Science', 'Engineering', 'Mathematics', 'Biological Sciences'], notable_features: ['Near DC', 'Strong CS', 'Big Ten'], has_volleyball: true, volleyball_division: 'D1', website: 'https://umd.edu' },
  { name: 'University of Florida', location: 'Gainesville, FL', state: 'FL', college_type: 'public', acceptance_rate: 23.0, sat_range_low: 1330, sat_range_high: 1490, act_range_low: 30, act_range_high: 34, enrollment: 60489, tuition_in_state: 6381, tuition_out_state: 28658, graduation_rate: 90, stem_ranking: 'Top 10 public', top_stem_programs: ['Computer Science', 'Engineering', 'AI', 'Biomedical Engineering'], notable_features: ['Preeminence funding', 'Lowest cost top public', 'Strong AI program'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ufl.edu' },
  { name: 'University of Colorado Boulder', location: 'Boulder, CO', state: 'CO', college_type: 'public', acceptance_rate: 80.0, sat_range_low: 1150, sat_range_high: 1370, act_range_low: 26, act_range_high: 31, enrollment: 40453, tuition_in_state: 13590, tuition_out_state: 41276, graduation_rate: 73, stem_ranking: 'Top 30 public', top_stem_programs: ['Aerospace Engineering', 'Physics', 'Computer Science', 'Environmental Science'], notable_features: ['Space research', 'Beautiful location', 'NOAA partnership'], has_volleyball: true, volleyball_division: 'D1', website: 'https://colorado.edu' },
  { name: 'Rose-Hulman Institute of Technology', location: 'Terre Haute, IN', state: 'IN', college_type: 'private', acceptance_rate: 64.0, sat_range_low: 1250, sat_range_high: 1440, act_range_low: 28, act_range_high: 33, enrollment: 2085, tuition_in_state: 56763, tuition_out_state: 56763, graduation_rate: 83, stem_ranking: '#1 undergraduate engineering (no PhD)', top_stem_programs: ['Engineering', 'Computer Science', 'Mathematics', 'Physics'], notable_features: ['#1 undergrad engineering', 'Small classes', 'Teaching focused'], has_volleyball: true, volleyball_division: 'D3', website: 'https://rose-hulman.edu' },
  { name: 'RPI (Rensselaer Polytechnic Institute)', location: 'Troy, NY', state: 'NY', college_type: 'private', acceptance_rate: 57.0, sat_range_low: 1330, sat_range_high: 1500, act_range_low: 30, act_range_high: 34, enrollment: 8152, tuition_in_state: 61320, tuition_out_state: 61320, graduation_rate: 84, stem_ranking: 'Top 20 engineering', top_stem_programs: ['Computer Science', 'Engineering', 'Architecture', 'IT'], notable_features: ['Oldest tech school in US', 'Strong gaming/VR', 'AI research'], has_volleyball: false, volleyball_division: null, website: 'https://rpi.edu' },
  { name: 'WPI (Worcester Polytechnic Institute)', location: 'Worcester, MA', state: 'MA', college_type: 'private', acceptance_rate: 55.0, sat_range_low: 1310, sat_range_high: 1470, act_range_low: 30, act_range_high: 33, enrollment: 7314, tuition_in_state: 58832, tuition_out_state: 58832, graduation_rate: 85, stem_ranking: 'Top 25 engineering', top_stem_programs: ['Robotics', 'Computer Science', 'Biomedical Engineering', 'Data Science'], notable_features: ['Project-based learning', '7-week terms', 'Global projects'], has_volleyball: true, volleyball_division: 'D3', website: 'https://wpi.edu' },
  { name: 'Case Western Reserve University', location: 'Cleveland, OH', state: 'OH', college_type: 'private', acceptance_rate: 30.0, sat_range_low: 1360, sat_range_high: 1510, act_range_low: 31, act_range_high: 34, enrollment: 12145, tuition_in_state: 58728, tuition_out_state: 58728, graduation_rate: 85, stem_ranking: 'Top 30', top_stem_programs: ['Biomedical Engineering', 'Computer Science', 'Engineering', 'Pre-Med'], notable_features: ['Cleveland Clinic partnership', 'Strong pre-med', 'Research focused'], has_volleyball: true, volleyball_division: 'D3', website: 'https://case.edu' },
  { name: 'Penn State University', location: 'State College, PA', state: 'PA', college_type: 'public', acceptance_rate: 55.0, sat_range_low: 1180, sat_range_high: 1370, act_range_low: 26, act_range_high: 31, enrollment: 88500, tuition_in_state: 19286, tuition_out_state: 38396, graduation_rate: 86, stem_ranking: 'Top 25 public', top_stem_programs: ['Engineering', 'Computer Science', 'Materials Science', 'Meteorology'], notable_features: ['Huge alumni network', 'Big Ten', 'Happy Valley'], has_volleyball: true, volleyball_division: 'D1', website: 'https://psu.edu' },
  { name: 'Ohio State University', location: 'Columbus, OH', state: 'OH', college_type: 'public', acceptance_rate: 53.0, sat_range_low: 1230, sat_range_high: 1430, act_range_low: 27, act_range_high: 33, enrollment: 61391, tuition_in_state: 11936, tuition_out_state: 35019, graduation_rate: 85, stem_ranking: 'Top 25 public', top_stem_programs: ['Computer Science', 'Engineering', 'Physics', 'Biomedical Science'], notable_features: ['Big Ten', 'Columbus tech scene', 'Large research'], has_volleyball: true, volleyball_division: 'D1', website: 'https://osu.edu' },
  { name: 'University of Minnesota', location: 'Minneapolis, MN', state: 'MN', college_type: 'public', acceptance_rate: 75.0, sat_range_low: 1240, sat_range_high: 1440, act_range_low: 27, act_range_high: 32, enrollment: 54953, tuition_in_state: 15478, tuition_out_state: 36402, graduation_rate: 82, stem_ranking: 'Top 25 public', top_stem_programs: ['Computer Science', 'Chemical Engineering', 'Biomedical Engineering'], notable_features: ['Twin Cities location', 'Medical device industry', 'Big Ten'], has_volleyball: true, volleyball_division: 'D1', website: 'https://umn.edu' },
  { name: 'NC State University', location: 'Raleigh, NC', state: 'NC', college_type: 'public', acceptance_rate: 47.0, sat_range_low: 1270, sat_range_high: 1430, act_range_low: 28, act_range_high: 33, enrollment: 37163, tuition_in_state: 9101, tuition_out_state: 30869, graduation_rate: 81, stem_ranking: 'Top 30 engineering', top_stem_programs: ['Computer Science', 'Engineering', 'Textiles', 'Statistics'], notable_features: ['Research Triangle', 'Co-op programs', 'Affordable'], has_volleyball: true, volleyball_division: 'D1', website: 'https://ncsu.edu' },
  { name: 'Stevens Institute of Technology', location: 'Hoboken, NJ', state: 'NJ', college_type: 'private', acceptance_rate: 41.0, sat_range_low: 1360, sat_range_high: 1500, act_range_low: 31, act_range_high: 34, enrollment: 8108, tuition_in_state: 60952, tuition_out_state: 60952, graduation_rate: 84, stem_ranking: 'Top 30 engineering', top_stem_programs: ['Computer Science', 'Cybersecurity', 'Engineering Management', 'AI'], notable_features: ['NYC proximity', 'Co-op program', 'Innovation focus'], has_volleyball: true, volleyball_division: 'D3', website: 'https://stevens.edu' },
  { name: 'Rochester Institute of Technology', location: 'Rochester, NY', state: 'NY', college_type: 'private', acceptance_rate: 63.0, sat_range_low: 1260, sat_range_high: 1430, act_range_low: 28, act_range_high: 33, enrollment: 19422, tuition_in_state: 56438, tuition_out_state: 56438, graduation_rate: 72, stem_ranking: 'Top 30 engineering', top_stem_programs: ['Computer Science', 'Engineering', 'Game Design', 'Cybersecurity', 'Imaging Science'], notable_features: ['Co-op required', 'Game design program', 'Deaf/hard-of-hearing services'], has_volleyball: true, volleyball_division: 'D3', website: 'https://rit.edu' },
  { name: 'Lehigh University', location: 'Bethlehem, PA', state: 'PA', college_type: 'private', acceptance_rate: 32.0, sat_range_low: 1330, sat_range_high: 1480, act_range_low: 30, act_range_high: 34, enrollment: 7522, tuition_in_state: 62180, tuition_out_state: 62180, graduation_rate: 89, stem_ranking: 'Top 30', top_stem_programs: ['Computer Science', 'Engineering', 'Materials Science', 'Industrial Engineering'], notable_features: ['Integrated business+engineering', 'Beautiful campus', 'Patriot League'], has_volleyball: true, volleyball_division: 'D1', website: 'https://lehigh.edu' },
]

export async function POST() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Check if already seeded
  const { count } = await supabase.from('colleges').select('*', { count: 'exact', head: true })
  if (count && count > 0) {
    return NextResponse.json({ message: `Already seeded with ${count} colleges` })
  }

  const { error } = await supabase.from('colleges').insert(COLLEGES)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ success: true, count: COLLEGES.length })
}

export async function GET() {
  const supabase = createClient()

  const { data, error } = await supabase
    .from('colleges')
    .select('*')
    .order('acceptance_rate', { ascending: true })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ colleges: data })
}
